[project]
name = "etl"
version = "0.1.0"
description = "ETL script that extracts the 1-Month SOFR forward rates"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []


[dependency-groups]
dev = [
    "ruff>=0.11.7",
]
