[project]
name = "api"
version = "0.1.0"
description = "Calculate the monthly floating interest given the maturity date rate floor, ceiling and spread"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []


[dependency-groups]
dev = [
    "ruff>=0.11.7",
]
